name: Update Data JSON

# Trigger this workflow every 2 minutes
on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 2 minutes
    
  # Optionally, run the workflow manually from GitHub Actions tab
  workflow_dispatch:

jobs:
  update-data-json:
    runs-on: ubuntu-latest  # Use an Ubuntu environment
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python (required to run Python scripts)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the Python version you need

      # Step 3: Install dependencies (if any)
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt || echo "No dependencies to install"

      # Step 4: Run the Python script (update_data.py)
      - name: Run update_json.py to update data.json
        run: python update_json.py

      # Step 5: Commit and push changes if data.json is updated
      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add data.json
          git commit -m "Update data.json via GitHub Actions" || echo "No changes to commit"
          git push origin main
